### PR TITLE
Obliquity function

### PR DESCRIPTION
**Pull request by frajazz**
Fix and improve
https://github.com/ari-zah/gaiasandbox/commit/b960e5ff38af4c70f629c86ba1b223915d02d99d

### CODE REVIEW

**Comment by langurmonkey** [comment]
Please, do not include your changes to config files (global.properties, gradle configuration, eclipse prefs) in your pull requests.
Also, I'm unable to find Rosetta, is it working for you?.

**Comment by frajazz** [comment]
Sorry more strange commit. I am trying to understand GitHub interface...
About Rosetta: if You talk about object position on the orbit - then You have to set not current date (set year = 2005 for instance)

**Comment by langurmonkey** [comment]
No problem, I will merge this when I have some time to sort it out. Thanks for the contribution!

**Comment by langurmonkey** [comment]
I have finally manually merged this (see 74a6217). However, the size of Cassini seems way too large, the model file is not normalised to 1. I can't change it (since it is a binary `.g3db` file), could you provide the source in `.obj` or `.blend` or something similar?

**Pull request closed without merging**
